version: '3.8'

services:
  assets.api:
    image: ${DOCKER_REGISTRY-}assetsapi
    build:
      context: .
      dockerfile: src/Services/Assets/Assets.API/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data: